// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tsfxkhgckxjpyjaegece.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzZnhraGdja3hqcHlqYWVnZWNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNzA0NjcsImV4cCI6MjA3Mzk0NjQ2N30.tlQ-lzB9KbVfJ7tbmYvv44NA_MJYxquV_QX1SbNKdwk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});